const os = require('os');
const fs = require('fs');
const path = require('path');

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  for (const name of Object.keys(interfaces)) {
    for (const iface of interfaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address;
      }
    }
  }
  return null;
}

const ip = getLocalIP();
if (!ip) {
  console.warn('⚠️  Could not detect local IP. Keeping existing .env');
  process.exit(0);
}

const envPath = path.join(__dirname, '..', '.env');
const content = `# Auto-generated by scripts/update-ip.js — do not edit manually
# Local development API URL
EXPO_PUBLIC_API_URL=http://${ip}:8000
`;

fs.writeFileSync(envPath, content);
console.log(`✅ API URL updated to: http://${ip}:8000`);
